### ISSUE TITLE
[Document][THANHHUONG] - Làm một tài liệu về cách triển khai code HTML, CSS

### ISSUE THREAD

**Issue by nhanntdl** [thanhhuong2020/thanhhuong2020.github.io#3]
Dear, @all

Anh cần mấy em làm giúp anh cách làm sao để code một số thứ sau đây bằng html và css:

> Custom theo phong cách hiện đại.

- [ ] thanh điều hướng #4 

- [x] nút bấm liên kết  #5 

- [x] nút bấm nộp giữ liệu #6 

- [x] textbox #7 

- [ ] combobox #8 

- [x] check box #9 

- [x] radio box #10 

- [ ] cách code html css theo kiểu [SOLID](https://viblo.asia/p/solid-la-gi-ap-dung-cac-nguyen-ly-solid-trong-thiet-ke-maGK7WELKj2) #11 

**Yêu cầu trong qua trình làm:**
- tạo wiki cho task này
- chụp ảnh màn hình để hiển thị **kết quả** của một đoạn code nào đó
- code ra file html, sử dụng thử <style></style> để định nghĩa css các custom
- lưu các file code ở thư mục: Documents\Wikis\Codes
- lưu các file hình ảnh hiển thị cho wiki ở thư mục: Documents\Wikis\Images
- tạo các liên kết từ file đến các file code ví dụ: Documents\Wikis\Codes\index.html
- dán code đã làm lên wiki

Please help me to documentation for this

Thanks and Best Regards
TrungNhan

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I will receive this work.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had complete this work.
Please check my work in [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/T%C3%A0i-li%E1%BB%87u-v%E1%BB%81-c%C3%A1ch-tri%E1%BB%83n-khai-code-html-v%C3%A0-css)
As for the "How to code html and css in SOLID style" part, I have not finished.

Thanks,
Lieu

**Comment by LieuTran287** [comment]
Dear @nhanntdl ,

I had completed this work.
Please check my work in [link](https://github.com/thanhhuong2020/thanhhuong2020.github.io/wiki/T%C3%A0i-li%E1%BB%87u-v%E1%BB%81-c%C3%A1ch-tri%E1%BB%83n-khai-code-html-v%C3%A0-css).

Thanks,
Lieu

**Comment by nhanntdl** [comment]
ok. còn phần còn lại anh sẽ support sau
